// Manages CRUD operations for Tasks
const taskModel = require('../models/Task');

// Create new task
const createTask = async (req, res) => {
    try {
        const newTask = new taskModel({
            title: req.body.title,
            status: req.body.status,
            priority: req.body.priority,
            deadline: req.body.deadline
        });
        // saved new task to MongoDB
        const savedTask = await newTask.save();
        // Send response with created saved task
        res.status(201).json(savedTask);
    } catch (err) {
        res.status(400).json({error: err.message});
    }
};

// Read/Load all tasks 
const readAllTask = async (req, res) => {
    try {
        const tasks = await taskModel.find();
        res.status(200).json(tasks);
    } catch (err) {
        res.status(400).json({error: err.message});
    }
};

// Read a single task by specific ID - ID is automatically generated by MongoDB
const readTaskByID = async (req, res) => {
    try {
        const task = await taskModel.findById(req.params.id);
        res.status(200).json(task);
    } catch (err) {
        res.status(400).json({error: err.message});
    }
};

// Update task
const updateTask = async (req, res) => {
    try {
        const updatedTask = await taskModel.findByIdAndUpdate(
            req.params.id,
            {
                title: req.body.title,
                status: req.body.status,
                priority: req.body.priority,
                deadline: req.body.deadline
            },
            { new: true, runValidators: true } // Return updated task & validate fields
        );
        if (!updatedTask) {
            return res.status(404).json({ message: 'Task not found' });
        }

        res.status(200).json(updatedTask);
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
};

// Delete task
const deleteTask = async (req, res) => {
    try {
        const deletedTask = await taskModel.findByIdAndDelete(req.params.id);
        if (!deletedTask) {
            return res.status(404).json({ message: 'Task not found' });
        }

        res.status(200).json({ message: 'Task deleted' });
    } catch (err) {
        res.status(400).json({ error: err.message });
    }
};

export { createTask, readAllTask, readTaskByID, updateTask, deleteTask };